<?php

namespace Ephemit\EvenementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository
{
    public function getPublicEvents($search){
        
        $recherche = "%".$search."%";
        
        $qb = $this->createQueryBuilder('e')
                ->where('(e.public = 1) AND (e.nom LIKE :recherche OR e.lieu LIKE :recherche OR e.description LIKE :recherche)')
                ->setParameter('recherche', $recherche)
                ->addOrderBy('e.nom', 'ASC');
        $res = $qb->getQuery()->getResult();

        return $res;
    }
}
